#spring:
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: llama2:latest
#          temperature: 0.7
spring:
  ai:
    google:
      gemini:
        # Gemini API Key from Google AI Studio
        api-key: AIzaSyCnF6Rqz6KyiMXYNtUf-SptWlA83zrocdA
        model: gemini-1.5-pro-latest
        default-options:
          temperature: 0.7
          safety-settings-threshold: BLOCK_NONE
server:
  port: 8080
